// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License..

#![crate_name = "helloworldsampleenclave"]
#![crate_type = "staticlib"]
#![cfg_attr(not(target_env = "sgx"), no_std)]
#![cfg_attr(target_env = "sgx", feature(rustc_private))]

extern crate bincode;
extern crate serde;
extern crate sgx_tcrypto;
extern crate sgx_types;
#[cfg(not(target_env = "sgx"))]
#[macro_use]
extern crate sgx_tstd as std;

use serde::{Deserialize, Serialize};
use sgx_tcrypto::*;
use sgx_types::*;
use std::mem::MaybeUninit;
use std::ptr;
use std::slice;
use std::sync::{Once, SgxMutex};
use std::vec::Vec;

// Generated by bindgen from enclave/my_struct.h
// Serialize and Deserialize are required by bincode/serde
#[repr(C)]
#[derive(Debug, Copy, Clone, Serialize, Deserialize)]
pub struct MyStruct {
    pub i: ::std::os::raw::c_int,
    pub f: f32,
}

struct EnclaveState {
    key: [u8; SGX_AESGCM_KEY_SIZE],
    iv: [u8; SGX_AESGCM_IV_SIZE],
    i: ::std::os::raw::c_int,
    f: f32,
}

// Rust doesn't support mutable statics, as it could lead to bugs in a multithreading setting
// and it cannot prevent this. So we need to use a mutex even if we have one thread
struct SingletonReader {
    inner: SgxMutex<EnclaveState>,
}

// From https://stackoverflow.com/questions/27791532/how-do-i-create-a-global-mutable-singleton
fn singleton() -> &'static SingletonReader {
    // Create an uninitialized static
    static mut SINGLETON: MaybeUninit<SingletonReader> = MaybeUninit::uninit();
    static ONCE: Once = Once::new();
    unsafe {
        ONCE.call_once(|| {
            // Make it
            let singleton = SingletonReader {
                inner: SgxMutex::new(EnclaveState {
                    key: [
                        0x1, 0x2, 0x3, 0x4, 0x5, 0x6, 0x7, 0x8, 0x9, 0xa, 0xb, 0xc, 0xd, 0xe, 0xf,
                        0x0,
                    ],
                    iv: [0x1, 0x2, 0x3, 0x4, 0x5, 0x6, 0x7, 0x8, 0x9, 0xa, 0xb, 0xc],
                    i: 0,
                    f: 0.0,
                }),
            };
            // Store it to the static var, i.e. initialize it
            SINGLETON.write(singleton);
        });

        // Now we give out a shared reference to the data, which is safe to use
        // concurrently.
        SINGLETON.assume_init_ref()
    }
}

/// An AES-GCM-128 encrypt function sample.
///
/// # Parameters
///
/// **plaintext**
///
/// Plain text to be encrypted.
///
/// **text_len**
///
/// Length of plain text, unsigned int.
///
/// **ciphertext**
///
/// A pointer to destination ciphertext buffer.
///
/// **mac**
///
/// A pointer to destination mac buffer, typed as &mut [u8;16].
///
/// # Return value
///
/// **SGX_SUCCESS** on success
///
/// # Errors
///
/// **SGX_ERROR_INVALID_PARAMETER** Indicates the parameter is invalid.
///
/// **SGX_ERROR_UNEXPECTED** Indicates that encryption failed.
///
/// # Requirements
///
/// The caller should allocate the ciphertext buffer. This buffer should be
/// at least same length as plaintext buffer. The caller should allocate the
/// mac buffer, at least 16 bytes.
// comes from samplecode/crypto
#[no_mangle]
pub extern "C" fn ecall_aes_gcm_128_encrypt(
    plaintext: *const u8,
    text_len: usize,
    ciphertext: *mut u8,
    mac: &mut [u8; 16],
) -> sgx_status_t {
    println!("aes_gcm_128_encrypt invoked!");

    let enclave_state = singleton().inner.lock().unwrap();
    let key = &enclave_state.key;
    let iv = &enclave_state.iv;

    // First, we need slices for input
    let plaintext_slice = unsafe { slice::from_raw_parts(plaintext, text_len) };

    // Here we need to initiate the ciphertext buffer, though nothing in it.
    // Thus show the length of ciphertext buffer is equal to plaintext buffer.
    // If not, the length of ciphertext_vec will be 0, which leads to argument
    // illegal.
    let mut ciphertext_vec: Vec<u8> = vec![0; text_len];

    // Second, for data with known length, we use array with fixed length.
    // Here we cannot use slice::from_raw_parts because it provides &[u8]
    // instead of &[u8,16].
    let aad_array: [u8; 0] = [0; 0];
    let mut mac_array: [u8; SGX_AESGCM_MAC_SIZE] = [0; SGX_AESGCM_MAC_SIZE];

    // Always check the length after slice::from_raw_parts
    if plaintext_slice.len() != text_len {
        return sgx_status_t::SGX_ERROR_INVALID_PARAMETER;
    }

    let ciphertext_slice = &mut ciphertext_vec[..];
    //println!(
    //    "aes_gcm_128_encrypt parameter prepared! {}, {}",
    //    plaintext_slice.len(),
    //    ciphertext_slice.len()
    //);

    // After everything has been set, call API
    let result = rsgx_rijndael128GCM_encrypt(
        key,
        &plaintext_slice,
        iv,
        &aad_array,
        ciphertext_slice,
        &mut mac_array,
    );
    //println!("rsgx calling returned!");

    // Match the result and copy result back to normal world.
    match result {
        Err(x) => {
            return x;
        }
        Ok(()) => {
            unsafe {
                ptr::copy_nonoverlapping(ciphertext_slice.as_ptr(), ciphertext, text_len);
            }
            *mac = mac_array;
        }
    }

    sgx_status_t::SGX_SUCCESS
}

/// An AES-GCM-128 decrypt function sample.
///
/// # Parameters
///
/// **ciphertext**
///
/// Cipher text to be decrypted.
///
/// **text_len**
///
/// Length of cipher text.
///
/// **mac**
///
/// A pointer to source mac buffer, typed as &[u8;16].
///
/// **plaintext**
///
/// A pointer to destination plaintext buffer.
///
/// # Return value
///
/// **SGX_SUCCESS** on success
///
/// # Errors
///
/// **SGX_ERROR_INVALID_PARAMETER** Indicates the parameter is invalid.
///
/// **SGX_ERROR_UNEXPECTED** means that decryption failed.
///
/// # Requirements
//
/// The caller should allocate the plaintext buffer. This buffer should be
/// at least same length as ciphertext buffer.
// comes from samplecode/crypto
#[no_mangle]
pub extern "C" fn ecall_aes_gcm_128_decrypt(
    ciphertext: *const u8,
    text_len: usize,
    mac: &[u8; 16],
    plaintext: *mut u8,
) -> sgx_status_t {
    println!("aes_gcm_128_decrypt invoked!");

    let enclave_state = singleton().inner.lock().unwrap();
    let key = &enclave_state.key;
    let iv = &enclave_state.iv;

    // First, for data with unknown length, we use vector as builder.
    let ciphertext_slice = unsafe { slice::from_raw_parts(ciphertext, text_len) };
    let mut plaintext_vec: Vec<u8> = vec![0; text_len];

    // Second, for data with known length, we use array with fixed length.
    let aad_array: [u8; 0] = [0; 0];

    if ciphertext_slice.len() != text_len {
        return sgx_status_t::SGX_ERROR_INVALID_PARAMETER;
    }

    let plaintext_slice = &mut plaintext_vec[..];
    //println!(
    //    "aes_gcm_128_decrypt parameter prepared! {}, {}",
    //    ciphertext_slice.len(),
    //    plaintext_slice.len()
    //);

    // After everything has been set, call API
    let result =
        rsgx_rijndael128GCM_decrypt(key, &ciphertext_slice, iv, &aad_array, mac, plaintext_slice);

    //println!("rsgx calling returned!");

    // Match the result and copy result back to normal world.
    match result {
        Err(x) => {
            return x;
        }
        Ok(()) => unsafe {
            ptr::copy_nonoverlapping(plaintext_slice.as_ptr(), plaintext, text_len);
        },
    }

    sgx_status_t::SGX_SUCCESS
}

#[no_mangle]
pub extern "C" fn ecall_bindgen_send_datastructure(s: MyStruct) {
    let mut enclave_state = singleton().inner.lock().unwrap();
    enclave_state.i = s.i;
    enclave_state.f = s.f;

    println!(
        "[ecall_bindgen] Set enclave state to n = {}, f = {}, done!",
        enclave_state.i, enclave_state.f
    );
}

#[no_mangle]
pub extern "C" fn ecall_bincode_send_datastructure(serialized: *const u8, len: usize) {
    let encoded = unsafe { slice::from_raw_parts(serialized, len) };
    let s: MyStruct = bincode::deserialize(&encoded[..]).unwrap();

    let mut enclave_state = singleton().inner.lock().unwrap();
    enclave_state.i = s.i;
    enclave_state.f = s.f;

    println!(
        "[ecall_bincode] Set enclave state to n = {}, f = {}, done!",
        enclave_state.i, enclave_state.f
    );
}
